apiVersion: v1 
kind: ConfigMap 
metadata:
  name: payment 
  namespace: roboshop 
data: 
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
  
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: payment 
  namespace: roboshop 
spec: 
  replicas: 1 
  selector:
    matchLabels:  
      app: payment 
      project: roboshop 
      tier: app 
  template:
    metadata:
      name: payment 
      labels:
        app: payment 
        project: roboshop 
        tier: app
    spec: 
      containers: 
      - name: payment 
        image: devopsprocloudaws/payment:1.0.0
        ports: 
        - containerPort: 8080 
        envFrom: 
        - configMapRef: # We need to put - because the devops-config has multiple key-value pairs
            name: payment 

--- 
apiVersion: v1 
kind: Service
metadata:
  name: payment
  namespace: roboshop 
spec: 
  selector: # selecting the Pod by using the same Pod labels 
    app: payment 
    project: roboshop 
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port 
    targetPort: 8080 # container port

