apiVersion: v1 
kind: ConfigMap 
metadata:
  name: shipping 
  namespace: roboshop 
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shipping 
  namespace: roboshop 
spec: 
  replicas: 1 
  selector:
    matchLabels:  
      app: shipping 
      project: roboshop 
      tier: app 
  template:
    metadata:
      name: shipping 
      labels:
        app: shipping 
        project: roboshop 
        tier: app
    spec: 
      containers: 
      - name: shipping 
        image: devopsprocloudaws/shipping:1.0.0
        ports: 
        - containerPort: 8080 
        envFrom: 
        - configMapRef: # We need to put - because the devops-config has multiple key-value pairs
            name: shipping 

--- 
apiVersion: v1 
kind: Service
metadata:
  name: shipping
  namespace: roboshop 
spec: 
  selector: # selecting the Pod by using the same Pod labels 
    app: shipping 
    project: roboshop 
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service port 
    targetPort: 8080 # container port

