apiVersion: v1 
kind: Secret 
metadata: 
  name: mysql 
type: Opaque 
data: 
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==

--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql 
  namespace: roboshop 
spec: 
  replicas: 1 
  selector:
    matchLabels:  
      app: mysql 
      project: roboshop 
      tier: db 
  template:
    metadata: 
      name: mysql 
      labels:
        app: mysql 
        project: roboshop 
        tier: db
    spec:   
      containers: 
      - name: mysql 
        image: devopsprocloudaws/mysql:1.0.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 3306 
        envFrom:
        - secretRef: 
            name: mysql 
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: mysql 
  namespace: roboshop
spec: 
  selector: # selecting the Pod by using the same Pod labels 
    app: mysql 
    project: roboshop 
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port 
    targetPort: 3306 # container port



